replicaCount: 1
revisionHistoryLimit: 0

image:
  repository: ghcr.io/florisfeddema/smartmeter-gateway-prometheus-exporter
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: [ ]

resources:
  limits:
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 16Mi

config:
  gatewayAddress: ''
