apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartmeter-gateway-prometheus-exporter
  labels:
    helm.sh/chart: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
      app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
        app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: smartmeter-gateway-prometheus-exporter
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        runAsNonRoot: true
      containers:
        - name: smartmeter-gateway-prometheus-exporter
          env:
            - name: SGPE_HOST
              value: {{ squote .Values.config.gatewayAddress }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            privileged: false
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
