apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smartmeter-gateway-prometheus-exporter
  labels:
    app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
      app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
  endpoints:
    - port: http
      path: /metrics
