apiVersion: v1
kind: Service
metadata:
  name: smartmeter-gateway-prometheus-exporter
  labels:
    helm.sh/chart: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/version: {{ .Chart.Version | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: smartmeter-gateway-prometheus-exporter
    app.kubernetes.io/instance: smartmeter-gateway-prometheus-exporter
